on:
  release:
    types: [created]
name: Handle Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: mattermost-server
      - name: Checkout client repo
        uses: actions/checkout@v2
        with:
          repository: bettermost/mattermost-webapp
          path: mattermost-webapp
      - name: Checkout enterprise repo
        uses: actions/checkout@v2
        with:
          repository: bettermost/mattermost-enterpriseoss
          path: mattermost-enterpriseoss
      - name: Pre-build
        run:  |
          ls
          sh  mattermost-server/scripts/pre-build.sh
      - name: Build
        run: |
          mv mattermost-enterpriseoss/enterprise .
          cd mattermost-server
          make build
          make build-client
          make package
      - name: Create Artifacts
        run: |
          mkdir release
          cp mattermost-server/dist/mattermost-enterprise-osx-amd64.tar.gz release/bettermost-oss-osx-amd64.tar.gz
          cp mattermost-server/dist/mattermost-enterprise-linux-amd64.tar.gz release/bettermost-oss-linux-amd64.tar.gz
          cp mattermost-server/dist/mattermost-enterprise-windows-amd64.zip release/bettermost-oss-windows-amd64.zip
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'release/bettermost*'
