on:
  release:
    types: [created]
name: Handle Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Build
        run: make build
      - name: Create Artifacts
        run: |
          mkdir release
          cp bin/mattermost release/mattermost_linux_amd64
          cp bin/darwin_amd64/mattermost release/mattermost_darwin_amd64
          cp bin/windows_amd64/mattermost.exe release/mattermost_windows_amd64.exe
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'release/mattermost*'
