on:
  release:
    types: [created]
name: Handle Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: mattermost-server
      - name: Checkout enterprise repo
        uses: actions/checkout@v2
        with:
          repository: bettermost/mattermost-enterpriseoss
          path: mattermost-enterpriseoss
      - name: Pre-build
        run:  |
          ls
          sh  mattermost-server/scripts/pre-build.sh
      - name: Build
        run: |
          mv mattermost-enterpriseoss/enterprise .
          cd mattermost-server
          make build
      - name: Create Artifacts
        run: |
          mkdir release
          cp mattermost-server/bin/mattermost release/mattermost_linux_amd64
          cp mattermost-server/bin/darwin_amd64/mattermost release/mattermost_darwin_amd64
          cp mattermost-server/bin/windows_amd64/mattermost.exe release/mattermost_windows_amd64.exe
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'release/mattermost*'
